-- Idempotent schema for pgvector readiness.
-- Safe to run multiple times.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "KnowledgeChunkEmbeddings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KnowledgeBaseId" bigint NOT NULL,
    "DocumentId" bigint NOT NULL,
    "ChunkId" bigint NOT NULL,
    "UserId" integer NOT NULL,
    "Model" varchar(120) NOT NULL DEFAULT '',
    "Dimension" integer NOT NULL DEFAULT 0,
    "Embedding" vector(1536) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_KnowledgeChunkEmbeddings_ChunkId_Model"
ON "KnowledgeChunkEmbeddings" ("ChunkId", "Model");

CREATE TABLE IF NOT EXISTS "AiResponseCaches" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CacheKey" varchar(200) NOT NULL,
    "Category" varchar(60) NOT NULL DEFAULT '',
    "Payload" text NOT NULL DEFAULT '',
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AiResponseCaches_CacheKey"
ON "AiResponseCaches" ("CacheKey");

CREATE INDEX IF NOT EXISTS "IX_AiResponseCaches_ExpiresAt"
ON "AiResponseCaches" ("ExpiresAt");

CREATE TABLE IF NOT EXISTS "AiToolTraceAudits" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "SessionId" bigint NULL,
    "Orchestrator" varchar(40) NOT NULL DEFAULT '',
    "ExecutionMode" varchar(20) NOT NULL DEFAULT '',
    "ToolName" varchar(120) NOT NULL DEFAULT '',
    "Source" varchar(60) NOT NULL DEFAULT '',
    "Status" varchar(20) NOT NULL DEFAULT '',
    "LatencyMs" integer NOT NULL DEFAULT 0,
    "RequestDigest" varchar(128) NOT NULL DEFAULT '',
    "ResponseDigest" varchar(128) NOT NULL DEFAULT '',
    "RequestPreview" varchar(600) NOT NULL DEFAULT '',
    "ResponsePreview" varchar(600) NOT NULL DEFAULT '',
    "ErrorCode" varchar(80) NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_AiToolTraceAudits_UserId_CreatedAt"
ON "AiToolTraceAudits" ("UserId", "CreatedAt");

CREATE INDEX IF NOT EXISTS "IX_AiToolTraceAudits_SessionId_CreatedAt"
ON "AiToolTraceAudits" ("SessionId", "CreatedAt");
